### ISSUE TITLE
Mark repo as [DEPRECATED] and "abandoned" on GitHub

### ISSUE THREAD

**Issue by GrahamCampbell** [php-http/httplug-stream-wrapper#3]
No public repos depend on this, and it has only been downloaded 15 times ever, and doesn't appear to be maintained?

**Comment by dbu** [comment]
@Nyholm wdyt? i vote for deleting the repository.

**Comment by Nyholm** [comment]
What is the reason for deleting it? It has not been a super high maintaining cost for this repo. 

It is a client like others but very unpopular.

**Comment by dbu** [comment]
it seems essentially unused, adding noise when doing things on all the php-http repositories. but if you want to keep it, i see no big harm either and would be fine with it. and maybe some people find it useful as an example to do their own stream wrapper things...

**Comment by GrahamCampbell** [comment]
So, it should be marked as abandoned, but not deleted?

**Comment by GrahamCampbell** [comment]
Ping. :)

**Comment by dbu** [comment]
marking as abandoned seems the right course of action to me. @Nyholm ok for you if i do that?

**Comment by Nyholm** [comment]
Sure

**Comment by dbu** [comment]
see #4
